// Generated by gencpp from file process/Job.msg
// DO NOT EDIT!


#ifndef PROCESS_MESSAGE_JOB_H
#define PROCESS_MESSAGE_JOB_H

#include <ros/service_traits.h>


#include <process/JobRequest.h>
#include <process/JobResponse.h>


namespace process
{

struct Job
{

typedef JobRequest Request;
typedef JobResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Job
} // namespace process


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::process::Job > {
  static const char* value()
  {
    return "0ada5c5b7449aa3c766d0b26140010e8";
  }

  static const char* value(const ::process::Job&) { return value(); }
};

template<>
struct DataType< ::process::Job > {
  static const char* value()
  {
    return "process/Job";
  }

  static const char* value(const ::process::Job&) { return value(); }
};


// service_traits::MD5Sum< ::process::JobRequest> should match
// service_traits::MD5Sum< ::process::Job >
template<>
struct MD5Sum< ::process::JobRequest>
{
  static const char* value()
  {
    return MD5Sum< ::process::Job >::value();
  }
  static const char* value(const ::process::JobRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::process::JobRequest> should match
// service_traits::DataType< ::process::Job >
template<>
struct DataType< ::process::JobRequest>
{
  static const char* value()
  {
    return DataType< ::process::Job >::value();
  }
  static const char* value(const ::process::JobRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::process::JobResponse> should match
// service_traits::MD5Sum< ::process::Job >
template<>
struct MD5Sum< ::process::JobResponse>
{
  static const char* value()
  {
    return MD5Sum< ::process::Job >::value();
  }
  static const char* value(const ::process::JobResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::process::JobResponse> should match
// service_traits::DataType< ::process::Job >
template<>
struct DataType< ::process::JobResponse>
{
  static const char* value()
  {
    return DataType< ::process::Job >::value();
  }
  static const char* value(const ::process::JobResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PROCESS_MESSAGE_JOB_H
