// Generated by gencpp from file process/JobResponse.msg
// DO NOT EDIT!


#ifndef PROCESS_MESSAGE_JOBRESPONSE_H
#define PROCESS_MESSAGE_JOBRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace process
{
template <class ContainerAllocator>
struct JobResponse_
{
  typedef JobResponse_<ContainerAllocator> Type;

  JobResponse_()
    : ok(0)  {
    }
  JobResponse_(const ContainerAllocator& _alloc)
    : ok(0)  {
  (void)_alloc;
    }



   typedef int32_t _ok_type;
  _ok_type ok;





  typedef boost::shared_ptr< ::process::JobResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::process::JobResponse_<ContainerAllocator> const> ConstPtr;

}; // struct JobResponse_

typedef ::process::JobResponse_<std::allocator<void> > JobResponse;

typedef boost::shared_ptr< ::process::JobResponse > JobResponsePtr;
typedef boost::shared_ptr< ::process::JobResponse const> JobResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::process::JobResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::process::JobResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::process::JobResponse_<ContainerAllocator1> & lhs, const ::process::JobResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ok == rhs.ok;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::process::JobResponse_<ContainerAllocator1> & lhs, const ::process::JobResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace process

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::process::JobResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::process::JobResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::process::JobResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::process::JobResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::process::JobResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::process::JobResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::process::JobResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b9dd14969ca0067602cf4f1d22022f4f";
  }

  static const char* value(const ::process::JobResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb9dd14969ca00676ULL;
  static const uint64_t static_value2 = 0x02cf4f1d22022f4fULL;
};

template<class ContainerAllocator>
struct DataType< ::process::JobResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "process/JobResponse";
  }

  static const char* value(const ::process::JobResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::process::JobResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 ok \n"
"\n"
;
  }

  static const char* value(const ::process::JobResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::process::JobResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ok);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JobResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::process::JobResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::process::JobResponse_<ContainerAllocator>& v)
  {
    s << indent << "ok: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ok);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROCESS_MESSAGE_JOBRESPONSE_H
