// Generated by gencpp from file process/YoloResponse.msg
// DO NOT EDIT!


#ifndef PROCESS_MESSAGE_YOLORESPONSE_H
#define PROCESS_MESSAGE_YOLORESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace process
{
template <class ContainerAllocator>
struct YoloResponse_
{
  typedef YoloResponse_<ContainerAllocator> Type;

  YoloResponse_()
    : position()
    , orientation(0.0)  {
      position.assign(0.0);
  }
  YoloResponse_(const ContainerAllocator& _alloc)
    : position()
    , orientation(0.0)  {
  (void)_alloc;
      position.assign(0.0);
  }



   typedef boost::array<float, 4>  _position_type;
  _position_type position;

   typedef float _orientation_type;
  _orientation_type orientation;





  typedef boost::shared_ptr< ::process::YoloResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::process::YoloResponse_<ContainerAllocator> const> ConstPtr;

}; // struct YoloResponse_

typedef ::process::YoloResponse_<std::allocator<void> > YoloResponse;

typedef boost::shared_ptr< ::process::YoloResponse > YoloResponsePtr;
typedef boost::shared_ptr< ::process::YoloResponse const> YoloResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::process::YoloResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::process::YoloResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::process::YoloResponse_<ContainerAllocator1> & lhs, const ::process::YoloResponse_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position &&
    lhs.orientation == rhs.orientation;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::process::YoloResponse_<ContainerAllocator1> & lhs, const ::process::YoloResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace process

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::process::YoloResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::process::YoloResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::process::YoloResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::process::YoloResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::process::YoloResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::process::YoloResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::process::YoloResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a6a0053a25879b9b6c76f23f3f2077dd";
  }

  static const char* value(const ::process::YoloResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa6a0053a25879b9bULL;
  static const uint64_t static_value2 = 0x6c76f23f3f2077ddULL;
};

template<class ContainerAllocator>
struct DataType< ::process::YoloResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "process/YoloResponse";
  }

  static const char* value(const ::process::YoloResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::process::YoloResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[4] position\n"
"float32 orientation \n"
"\n"
;
  }

  static const char* value(const ::process::YoloResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::process::YoloResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.orientation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct YoloResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::process::YoloResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::process::YoloResponse_<ContainerAllocator>& v)
  {
    s << indent << "position[]" << std::endl;
    for (size_t i = 0; i < v.position.size(); ++i)
    {
      s << indent << "  position[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.position[i]);
    }
    s << indent << "orientation: ";
    Printer<float>::stream(s, indent + "  ", v.orientation);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROCESS_MESSAGE_YOLORESPONSE_H
