// Generated by gencpp from file process/Yolo.msg
// DO NOT EDIT!


#ifndef PROCESS_MESSAGE_YOLO_H
#define PROCESS_MESSAGE_YOLO_H

#include <ros/service_traits.h>


#include <process/YoloRequest.h>
#include <process/YoloResponse.h>


namespace process
{

struct Yolo
{

typedef YoloRequest Request;
typedef YoloResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Yolo
} // namespace process


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::process::Yolo > {
  static const char* value()
  {
    return "2324e6725e41ae1ab2f6b532bc848fe5";
  }

  static const char* value(const ::process::Yolo&) { return value(); }
};

template<>
struct DataType< ::process::Yolo > {
  static const char* value()
  {
    return "process/Yolo";
  }

  static const char* value(const ::process::Yolo&) { return value(); }
};


// service_traits::MD5Sum< ::process::YoloRequest> should match
// service_traits::MD5Sum< ::process::Yolo >
template<>
struct MD5Sum< ::process::YoloRequest>
{
  static const char* value()
  {
    return MD5Sum< ::process::Yolo >::value();
  }
  static const char* value(const ::process::YoloRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::process::YoloRequest> should match
// service_traits::DataType< ::process::Yolo >
template<>
struct DataType< ::process::YoloRequest>
{
  static const char* value()
  {
    return DataType< ::process::Yolo >::value();
  }
  static const char* value(const ::process::YoloRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::process::YoloResponse> should match
// service_traits::MD5Sum< ::process::Yolo >
template<>
struct MD5Sum< ::process::YoloResponse>
{
  static const char* value()
  {
    return MD5Sum< ::process::Yolo >::value();
  }
  static const char* value(const ::process::YoloResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::process::YoloResponse> should match
// service_traits::DataType< ::process::Yolo >
template<>
struct DataType< ::process::YoloResponse>
{
  static const char* value()
  {
    return DataType< ::process::Yolo >::value();
  }
  static const char* value(const ::process::YoloResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PROCESS_MESSAGE_YOLO_H
