// Generated by gencpp from file process/YoloRequest.msg
// DO NOT EDIT!


#ifndef PROCESS_MESSAGE_YOLOREQUEST_H
#define PROCESS_MESSAGE_YOLOREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace process
{
template <class ContainerAllocator>
struct YoloRequest_
{
  typedef YoloRequest_<ContainerAllocator> Type;

  YoloRequest_()
    : id(0)
    , demand(0)
    , location(0)  {
    }
  YoloRequest_(const ContainerAllocator& _alloc)
    : id(0)
    , demand(0)
    , location(0)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef int32_t _demand_type;
  _demand_type demand;

   typedef int32_t _location_type;
  _location_type location;





  typedef boost::shared_ptr< ::process::YoloRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::process::YoloRequest_<ContainerAllocator> const> ConstPtr;

}; // struct YoloRequest_

typedef ::process::YoloRequest_<std::allocator<void> > YoloRequest;

typedef boost::shared_ptr< ::process::YoloRequest > YoloRequestPtr;
typedef boost::shared_ptr< ::process::YoloRequest const> YoloRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::process::YoloRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::process::YoloRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::process::YoloRequest_<ContainerAllocator1> & lhs, const ::process::YoloRequest_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.demand == rhs.demand &&
    lhs.location == rhs.location;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::process::YoloRequest_<ContainerAllocator1> & lhs, const ::process::YoloRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace process

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::process::YoloRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::process::YoloRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::process::YoloRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::process::YoloRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::process::YoloRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::process::YoloRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::process::YoloRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "67a6c1038c1e52453c59238bdb4b5818";
  }

  static const char* value(const ::process::YoloRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x67a6c1038c1e5245ULL;
  static const uint64_t static_value2 = 0x3c59238bdb4b5818ULL;
};

template<class ContainerAllocator>
struct DataType< ::process::YoloRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "process/YoloRequest";
  }

  static const char* value(const ::process::YoloRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::process::YoloRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n"
"int32 demand \n"
"int32 location\n"
;
  }

  static const char* value(const ::process::YoloRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::process::YoloRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.demand);
      stream.next(m.location);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct YoloRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::process::YoloRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::process::YoloRequest_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "demand: ";
    Printer<int32_t>::stream(s, indent + "  ", v.demand);
    s << indent << "location: ";
    Printer<int32_t>::stream(s, indent + "  ", v.location);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROCESS_MESSAGE_YOLOREQUEST_H
