// Generated by gencpp from file airobots_ammr/Job.msg
// DO NOT EDIT!


#ifndef AIROBOTS_AMMR_MESSAGE_JOB_H
#define AIROBOTS_AMMR_MESSAGE_JOB_H

#include <ros/service_traits.h>


#include <airobots_ammr/JobRequest.h>
#include <airobots_ammr/JobResponse.h>


namespace airobots_ammr
{

struct Job
{

typedef JobRequest Request;
typedef JobResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Job
} // namespace airobots_ammr


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::airobots_ammr::Job > {
  static const char* value()
  {
    return "121b506e876d46cc88efd65664c7abde";
  }

  static const char* value(const ::airobots_ammr::Job&) { return value(); }
};

template<>
struct DataType< ::airobots_ammr::Job > {
  static const char* value()
  {
    return "airobots_ammr/Job";
  }

  static const char* value(const ::airobots_ammr::Job&) { return value(); }
};


// service_traits::MD5Sum< ::airobots_ammr::JobRequest> should match
// service_traits::MD5Sum< ::airobots_ammr::Job >
template<>
struct MD5Sum< ::airobots_ammr::JobRequest>
{
  static const char* value()
  {
    return MD5Sum< ::airobots_ammr::Job >::value();
  }
  static const char* value(const ::airobots_ammr::JobRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::airobots_ammr::JobRequest> should match
// service_traits::DataType< ::airobots_ammr::Job >
template<>
struct DataType< ::airobots_ammr::JobRequest>
{
  static const char* value()
  {
    return DataType< ::airobots_ammr::Job >::value();
  }
  static const char* value(const ::airobots_ammr::JobRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::airobots_ammr::JobResponse> should match
// service_traits::MD5Sum< ::airobots_ammr::Job >
template<>
struct MD5Sum< ::airobots_ammr::JobResponse>
{
  static const char* value()
  {
    return MD5Sum< ::airobots_ammr::Job >::value();
  }
  static const char* value(const ::airobots_ammr::JobResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::airobots_ammr::JobResponse> should match
// service_traits::DataType< ::airobots_ammr::Job >
template<>
struct DataType< ::airobots_ammr::JobResponse>
{
  static const char* value()
  {
    return DataType< ::airobots_ammr::Job >::value();
  }
  static const char* value(const ::airobots_ammr::JobResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AIROBOTS_AMMR_MESSAGE_JOB_H
