// Generated by gencpp from file airobots_ammr/JobResponse.msg
// DO NOT EDIT!


#ifndef AIROBOTS_AMMR_MESSAGE_JOBRESPONSE_H
#define AIROBOTS_AMMR_MESSAGE_JOBRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace airobots_ammr
{
template <class ContainerAllocator>
struct JobResponse_
{
  typedef JobResponse_<ContainerAllocator> Type;

  JobResponse_()
    : ok(0)  {
    }
  JobResponse_(const ContainerAllocator& _alloc)
    : ok(0)  {
  (void)_alloc;
    }



   typedef int8_t _ok_type;
  _ok_type ok;





  typedef boost::shared_ptr< ::airobots_ammr::JobResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::airobots_ammr::JobResponse_<ContainerAllocator> const> ConstPtr;

}; // struct JobResponse_

typedef ::airobots_ammr::JobResponse_<std::allocator<void> > JobResponse;

typedef boost::shared_ptr< ::airobots_ammr::JobResponse > JobResponsePtr;
typedef boost::shared_ptr< ::airobots_ammr::JobResponse const> JobResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::airobots_ammr::JobResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::airobots_ammr::JobResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::airobots_ammr::JobResponse_<ContainerAllocator1> & lhs, const ::airobots_ammr::JobResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ok == rhs.ok;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::airobots_ammr::JobResponse_<ContainerAllocator1> & lhs, const ::airobots_ammr::JobResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace airobots_ammr

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::airobots_ammr::JobResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::airobots_ammr::JobResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::airobots_ammr::JobResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::airobots_ammr::JobResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::airobots_ammr::JobResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::airobots_ammr::JobResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::airobots_ammr::JobResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "719c501bbbeb289704ee5d42501844db";
  }

  static const char* value(const ::airobots_ammr::JobResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x719c501bbbeb2897ULL;
  static const uint64_t static_value2 = 0x04ee5d42501844dbULL;
};

template<class ContainerAllocator>
struct DataType< ::airobots_ammr::JobResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "airobots_ammr/JobResponse";
  }

  static const char* value(const ::airobots_ammr::JobResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::airobots_ammr::JobResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 ok\n"
;
  }

  static const char* value(const ::airobots_ammr::JobResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::airobots_ammr::JobResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ok);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JobResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::airobots_ammr::JobResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::airobots_ammr::JobResponse_<ContainerAllocator>& v)
  {
    s << indent << "ok: ";
    Printer<int8_t>::stream(s, indent + "  ", v.ok);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AIROBOTS_AMMR_MESSAGE_JOBRESPONSE_H
