// Generated by gencpp from file airobots_ammr/JobRequest.msg
// DO NOT EDIT!


#ifndef AIROBOTS_AMMR_MESSAGE_JOBREQUEST_H
#define AIROBOTS_AMMR_MESSAGE_JOBREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace airobots_ammr
{
template <class ContainerAllocator>
struct JobRequest_
{
  typedef JobRequest_<ContainerAllocator> Type;

  JobRequest_()
    : ammr_location(0)  {
    }
  JobRequest_(const ContainerAllocator& _alloc)
    : ammr_location(0)  {
  (void)_alloc;
    }



   typedef int32_t _ammr_location_type;
  _ammr_location_type ammr_location;





  typedef boost::shared_ptr< ::airobots_ammr::JobRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::airobots_ammr::JobRequest_<ContainerAllocator> const> ConstPtr;

}; // struct JobRequest_

typedef ::airobots_ammr::JobRequest_<std::allocator<void> > JobRequest;

typedef boost::shared_ptr< ::airobots_ammr::JobRequest > JobRequestPtr;
typedef boost::shared_ptr< ::airobots_ammr::JobRequest const> JobRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::airobots_ammr::JobRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::airobots_ammr::JobRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::airobots_ammr::JobRequest_<ContainerAllocator1> & lhs, const ::airobots_ammr::JobRequest_<ContainerAllocator2> & rhs)
{
  return lhs.ammr_location == rhs.ammr_location;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::airobots_ammr::JobRequest_<ContainerAllocator1> & lhs, const ::airobots_ammr::JobRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace airobots_ammr

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::airobots_ammr::JobRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::airobots_ammr::JobRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::airobots_ammr::JobRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::airobots_ammr::JobRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::airobots_ammr::JobRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::airobots_ammr::JobRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::airobots_ammr::JobRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "00dde7b94c8a24312535a86f6dacc224";
  }

  static const char* value(const ::airobots_ammr::JobRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x00dde7b94c8a2431ULL;
  static const uint64_t static_value2 = 0x2535a86f6dacc224ULL;
};

template<class ContainerAllocator>
struct DataType< ::airobots_ammr::JobRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "airobots_ammr/JobRequest";
  }

  static const char* value(const ::airobots_ammr::JobRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::airobots_ammr::JobRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 ammr_location\n"
;
  }

  static const char* value(const ::airobots_ammr::JobRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::airobots_ammr::JobRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ammr_location);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JobRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::airobots_ammr::JobRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::airobots_ammr::JobRequest_<ContainerAllocator>& v)
  {
    s << indent << "ammr_location: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ammr_location);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AIROBOTS_AMMR_MESSAGE_JOBREQUEST_H
