// Generated by gencpp from file airobots_ammr/Yolo.msg
// DO NOT EDIT!


#ifndef AIROBOTS_AMMR_MESSAGE_YOLO_H
#define AIROBOTS_AMMR_MESSAGE_YOLO_H

#include <ros/service_traits.h>


#include <airobots_ammr/YoloRequest.h>
#include <airobots_ammr/YoloResponse.h>


namespace airobots_ammr
{

struct Yolo
{

typedef YoloRequest Request;
typedef YoloResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Yolo
} // namespace airobots_ammr


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::airobots_ammr::Yolo > {
  static const char* value()
  {
    return "7b27c6abe40c22cf4eac73520da2bb11";
  }

  static const char* value(const ::airobots_ammr::Yolo&) { return value(); }
};

template<>
struct DataType< ::airobots_ammr::Yolo > {
  static const char* value()
  {
    return "airobots_ammr/Yolo";
  }

  static const char* value(const ::airobots_ammr::Yolo&) { return value(); }
};


// service_traits::MD5Sum< ::airobots_ammr::YoloRequest> should match
// service_traits::MD5Sum< ::airobots_ammr::Yolo >
template<>
struct MD5Sum< ::airobots_ammr::YoloRequest>
{
  static const char* value()
  {
    return MD5Sum< ::airobots_ammr::Yolo >::value();
  }
  static const char* value(const ::airobots_ammr::YoloRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::airobots_ammr::YoloRequest> should match
// service_traits::DataType< ::airobots_ammr::Yolo >
template<>
struct DataType< ::airobots_ammr::YoloRequest>
{
  static const char* value()
  {
    return DataType< ::airobots_ammr::Yolo >::value();
  }
  static const char* value(const ::airobots_ammr::YoloRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::airobots_ammr::YoloResponse> should match
// service_traits::MD5Sum< ::airobots_ammr::Yolo >
template<>
struct MD5Sum< ::airobots_ammr::YoloResponse>
{
  static const char* value()
  {
    return MD5Sum< ::airobots_ammr::Yolo >::value();
  }
  static const char* value(const ::airobots_ammr::YoloResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::airobots_ammr::YoloResponse> should match
// service_traits::DataType< ::airobots_ammr::Yolo >
template<>
struct DataType< ::airobots_ammr::YoloResponse>
{
  static const char* value()
  {
    return DataType< ::airobots_ammr::Yolo >::value();
  }
  static const char* value(const ::airobots_ammr::YoloResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AIROBOTS_AMMR_MESSAGE_YOLO_H
